export const products = [
    {
      id: 1,
      nameKey: 'products.naturalSoap',
      descriptionKey: 'products.naturalSoapDesc',
      price: 30,
      category: 'soap',
      image: '/assets/natural.jpg',
    },
    {
      id: 2,
      nameKey: 'products.herbalSoap',
      descriptionKey: 'products.herbalSoapDesc',
      price: 28,
      category: 'soap',
      image: '/assets/herbal.jpg',
    },
    {
      id: 3,
      nameKey: 'products.vitaminCSerum',
      descriptionKey: 'products.vitaminCSerumDesc',
      price: 120,
      category: 'serum',
      image: '/assets/VitaminC.jpg',
    },
    {
      id: 4,
      nameKey: 'products.hydratingSerum',
      descriptionKey: 'products.hydratingSerumDesc',
      price: 110,
      category: 'serum',
      image: '/assets/Hydrating.jpg',
    },
    {
      id: 5,
      nameKey: 'products.organicLipOil',
      descriptionKey: 'products.organicLipOilDesc',
      price: 50,
      category: 'lip',
      image: '/assets/LipOil.jpg',
    },
    {
      id: 6,
      nameKey: 'products.glossyLipOil',
      descriptionKey: 'products.glossyLipOilDesc',
      price: 55,
      category: 'lip',
      image: '/assets/GlossyLip.jpg',
    },
    {
      id: 7,
      nameKey: 'products.arganOil',
      descriptionKey: 'products.arganOilDesc',
      price: 85,
      category: 'oil',
      image: '/assets/ArganOil.jpg',
    },
    {
      id: 8,
      nameKey: 'products.rosehipOil',
      descriptionKey: 'products.rosehipOilDesc',
      price: 90,
      category: 'oil',
      image: '/assets/Rosehip.jpg',
    },
    {
      id: 9,
      nameKey: 'products.honeySoap',
      descriptionKey: 'products.honeySoapDesc',
      price: 25,
      category: 'soap',
      image: '/assets/honey.jpg',
    },
    {
      id: 10,
      nameKey: 'products.charcoalSoap',
      descriptionKey: 'products.charcoalSoapDesc',
      price: 35,
      category: 'soap',
      image: '/assets/Charcoal.jpg',
    },
    {
      id: 11,
      nameKey: 'products.glowSerum',
      descriptionKey: 'products.glowSerumDesc',
      price: 115,
      category: 'serum',
      image: '/assets/serum.jpg',
    },
    {
      id: 12,
      nameKey: 'products.antiAgingSerum',
      descriptionKey: 'products.antiAgingSerumDesc',
      price: 130,
      category: 'serum',
      image: '/assets/AntiAging.jpg',
    },
    {
      id: 13,
      nameKey: 'products.mintLipOil',
      descriptionKey: 'products.mintLipOilDesc',
      price: 48,
      category: 'lip',
      image: '/assets/MintLip.jpg',
    },
    {
      id: 14,
      nameKey: 'products.tintedLipOil',
      descriptionKey: 'products.tintedLipOilDesc',
      price: 52,
      category: 'lip',
      image: '/assets/TintedLip.jpg',
    },
    {
      id: 15,
      nameKey: 'products.lavenderOil',
      descriptionKey: 'products.lavenderOilDesc',
      price: 92,
      category: 'oil',
      image: '/assets/Lavender.jpg',
    },
    {
      id: 16,
      nameKey: 'products.coconutOil',
      descriptionKey: 'products.coconutOilDesc',
      price: 78,
      category: 'oil',
      image: '/assets/Coconut.jpg',
    },
  ];
  